SELECT 'CREATE DATABASE CV'
WHERE NOT EXISTS(SELECT FROM PG_DATABASE WHERE DATNAME = 'CV');
\gexec

CREATE TABLE IF NOT EXISTS Users
(
	id SERIAL PRIMARY KEY,
	name VARCHAR UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	is_admin BOOLEAN DEFAULT FALSE,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Requests
(
	id SERIAL PRIMARY KEY,
	author_id INTEGER NOT NULL,
	candidate_name VARCHAR NOT NULL,
	candidate_surname VARCHAR NOT NULL,
	cv_file_id INTEGER NOT NULL,
	status VARCHAR CHECK (
		Status = 'Accepted' OR
		Status = 'Rejected' OR
		Status = 'Submitted'
	) DEFAULT 'Submitted',
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fkUser
		FOREIGN KEY(author_id)
			REFERENCES Users(id)
);
