linters:
  disable:
    - dupl
    - funlen
    - goconst
    - lll
    - gofumpt
    - gochecknoglobals
    - revive
    - scopelint
    - gosec
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - interfacer
    - gas
    - maligned
    - prealloc
    