runtime: go116

main: ./cmd

env_variables:
  GOOGLE_BUCKET_NAME: "referral-itech"

  GCS_CREDENTIALS_PATH: "credentials.json"

  DB_HOST: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "Server1"
  DB_NAME: "CV"
  DB_PORT: "5432"
  DB_SSLMODE: "disable"

  APP_PORT: "8000"

  JWT_KEY: "Str0ngP@$$w0rd?##"
  JWT_EXPIRY_TIME: "20"
