version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Server1
      - POSTGRES_DB=CV
    volumes:
      - ./scripts/init:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
