version: '3'

services:
  postgres:
    container_name: referral-test-container
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Server1
      - POSTGRES_DB=CV
    volumes:
      - ./scripts/init/_main_script.sql:/docker-entrypoint-initdb.d/_main_script.sql
    ports:
      - 5432:5432
