version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - database.env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
