CREATE DATABASE IF NOT EXISTS CV

CREATE TABLE IF NOT EXISTS Users
(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR UNIQUE NOT NULL,
	Password VARCHAR NOT NULL,
	Type VARCHAR CHECK (
		Type = 'Admin' OR
		Type = 'User'
	) DEFAULT 'User',
	Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Candidates
(
	Id SERIAL PRIMARY KEY,
	RequestId INTEGER NOT NULL,
	Name VARCHAR NOT NULL,
	Surname VARCHAR NOT NULL,
	CONSTRAINT fkRequest
		FOREIGN KEY(RequestId)
			REFERENCES Requests(Id)
);

CREATE TABLE IF NOT EXISTS CVs
(
	Id SERIAL PRIMARY KEY,
	CandidateId INTEGER NOT NULL,
	OSFileId INTEGER,
	CONSTRAINT fkCandidate
		FOREIGN KEY(CandidateId)
			REFERENCES Candidates(Id)
);

CREATE TABLE IF NOT EXISTS Requests
(
	Id SERIAL PRIMARY KEY,
	UserId INTEGER NOT NULL,
	Status VARCHAR CHECK (
		Status = 'Accepted' OR
		Status = 'Rejected' OR
		Status = 'Submitted' OR
		Status = 'Pending'
	) DEFAULT 'Pending',
	Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fkUser
		FOREIGN KEY(UserId)
			REFERENCES Users(Id)
);
