name: build-push

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get shrt commit sha
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA::7})

#      - name: Build app image
#        run : docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/referral .
#
#      - name: Tag image
#        run : |
#          docker tag referral ${{ secrets.DOCKERHUB_USERNAME }}/referral:${{steps.vars.outputs.tag}}
#          docker tag referral ${{ secrets.DOCKERHUB_USERNAME }}/referral:latest
#
#      - name: Push image
#        run : docker push ${{ secrets.DOCKERHUB_USERNAME }}/referral:latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/referral:${{steps.vars.outputs.tag}}, ${{ secrets.DOCKERHUB_USERNAME }}/referral:latest