name: build-push

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get shrt commit sha
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA::7})

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: referral:${{steps.vars.outputs.tag}}, referral:latest