name: testing

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Server1
          POSTGRES_DB: CV
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create database
        run: psql -h localhost -U postgres -d CV -f scripts/init/_main_script.sql
        env:
          PGPASSWORD: Server1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: Execute unit tests
        run : go test -v ./internal/*

      - name: Execute integration tests
        run : go test -v ./tests
