name: testing

on:
  pull_request:
    branches:
      - main

env:
  DB_HOST: localhost
  DB_USER: postgres
  DB_PASSWORD: Server1
  DB_NAME: CV
  DB_PORT: 5432
  DB_SSLMODE: disable

jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: ${{env.DB_USER}}
          POSTGRES_PASSWORD: ${{env.DB_PASSWORD}}
          POSTGRES_DB: ${{env.DB_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create database
        run: psql -h ${{env.DB_HOST}} -U ${{env.DB_USER}} -d ${{env.DB_NAME}} -f scripts/init/_main_script.sql
        env:
          PGPASSWORD: ${{env.DB_PASSWORD}}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.3'

      - name: Execute unit tests
        run : go test -v ./internal/*

      - name: Execute integration tests
        run : go test -v ./tests
