name: testing

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create application image
        run : docker build -t referral .

      - name: Execute docker-compose
        run : docker-compose up -d

      - name: Execute unit tests
        run : go test -v ./internal/*

      - name: Execute integration tests
        run : go test -v ./tests
